<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { isAxiosError } from 'axios'
import { list, type Roster } from '@/api/rosters'

const rosters = ref<Roster[]>([])
const loading = ref(true)
const error = ref('')

const monthLabels = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
]

function formatPeriod(roster: Roster): string {
  const monthName = monthLabels[roster.month - 1] ?? String(roster.month)

  return `${monthName} ${roster.year}`
}

function formatGeneratedAt(value: string | null): string {
  if (value === null) {
    return '-'
  }

  return new Date(value).toLocaleString()
}

function statusClass(status: Roster['status']): string {
  if (status === 'published') {
    return 'badge badge--success'
  }

  if (status === 'superseded') {
    return 'badge badge--muted'
  }

  return 'badge'
}

onMounted(async () => {
  loading.value = true
  error.value = ''

  try {
    const response = await list()
    rosters.value = response.data
  } catch (err) {
    if (isAxiosError(err) && err.response?.data?.message) {
      error.value = String(err.response.data.message)
    } else {
      error.value = 'Could not load rosters. Please try again.'
    }
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <main class="page">
    <header class="page__header">
      <div>
        <p class="page__eyebrow">Rosters</p>
        <h1 class="page__title">Saved Rosters</h1>
        <p class="page__description">Browse draft and published rosters generated by the engine.</p>
      </div>
      <div class="page__actions">
        <RouterLink class="button button--primary" :to="{ name: 'rosters.generate' }">
          Generate roster
        </RouterLink>
      </div>
    </header>

    <section class="panel">
      <div v-if="error" class="alert" role="alert">
        {{ error }}
      </div>

      <div class="table-wrap">
        <table class="table">
          <thead>
            <tr>
              <th>Period</th>
              <th>Status</th>
              <th>Assignments</th>
              <th>Generated</th>
              <th class="table__actions">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="loading">
              <td colspan="5" class="table__empty">Loading rosters...</td>
            </tr>
            <tr v-else-if="rosters.length === 0">
              <td colspan="5" class="table__empty">No saved rosters yet.</td>
            </tr>
            <tr v-for="roster in rosters" :key="roster.id">
              <td><strong>{{ formatPeriod(roster) }}</strong></td>
              <td>
                <span :class="statusClass(roster.status)">{{ roster.status }}</span>
              </td>
              <td>{{ roster.assignment_count ?? 0 }}</td>
              <td>{{ formatGeneratedAt(roster.generated_at) }}</td>
              <td class="table__actions">
                <RouterLink class="button" :to="{ name: 'rosters.show', params: { id: roster.id } }">
                  Edit 
                </RouterLink>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  </main>
</template>
